metadata:
  name: bench-session
  format: "Lava-Test-Shell Test Definition 1.0"
  description: "Benchmarking Session"
  version: 1.0

params:
    PUB_KEY: None

install:
    deps:
        - openssh-server
        - wget
        - make
        - cpufrequtils
        - binutils
        - gawk
        - libgfortran3
        - rsync

run:
    steps:
        - ./config/bench/lava/setup "$PUB_KEY"
        - ./config/bench/lava/target-session
