job_name: '${LAVA_JOB_NAME}'
timeout: ${TIMEOUT}
actions:
  - command: '${HOST_DEPLOY_ACTION}'
    parameters:
      role: host
      ${HOST_IMAGE_1}
      ${HOST_IMAGE_2}
      ${HOST_IMAGE_3}
  - command: '${TARGET_DEPLOY_ACTION}'
    parameters:
      role: target
      #TODO: This is horrid, but will have to do for now
      ${TARGET_IMAGE_1}
      ${TARGET_IMAGE_2}
      ${TARGET_IMAGE_3}
    metadata:
      ${METADATA_1}
      ${METADATA_2}
      ${METADATA_3}
      ${METADATA_4}
      ${METADATA_5}
      ${METADATA_6}
      ${METADATA_7}
      ${METADATA_8}
      ${METADATA_9}
      ${METADATA_10}
      ${METADATA_11}
      ${METADATA_12}
      ${METADATA_13}
      ${METADATA_14}
      ${METADATA_15}
      ${METADATA_16}
      ${METADATA_17}
      ${METADATA_18}
      ${METADATA_19}
      ${METADATA_20}
      ${METADATA_21}
      ${METADATA_22}
      ${METADATA_23}
      ${METADATA_24}
      ${METADATA_25}
      ${METADATA_26}
      ${METADATA_27}
      ${METADATA_28}
      ${METADATA_29}
      ${METADATA_30}
      ${METADATA_31}
      ${METADATA_32}
      ${METADATA_33}
      ${METADATA_34}
      ${METADATA_35}
      ${METADATA_36}
      ${METADATA_37}
      ${METADATA_38}
      ${METADATA_39}
      ${METADATA_40}
      ${METADATA_41}
      ${METADATA_42}
      ${METADATA_43}
      ${METADATA_44}
      ${METADATA_45}
      ${METADATA_46}
      ${METADATA_47}
      ${METADATA_48}
      ${METADATA_49}
      ${METADATA_50}
  - command: lava_test_shell
    parameters:
      role: host
      timeout: ${TIMEOUT}
      testdef_repos:
        - git-repo: '${TESTDEF_REPO}'
          revision: '${TESTDEF_REVISION}'
          testdef: '${HOST_SESSION}'
          parameters:
            BENCHMARK: '${BENCHMARK}'
            TOOLCHAIN: '${TOOLCHAIN}'
            TRIPLE: '${TRIPLE}'
            SYSROOT: '${SYSROOT}'
            RUN_FLAGS: '${RUN_FLAGS}'
            COMPILER_FLAGS: '${COMPILER_FLAGS}'
            MAKE_FLAGS: '${MAKE_FLAGS}'
            PREBUILT: '${PREBUILT}'
            BENCH_DEBUG: 1
            TRUST: 'None'
            PUB_KEY: '${PUBLIC_KEY}'
  - command: lava_test_shell
    parameters:
      role: target
      timeout: ${TIMEOUT}
      testdef_repos:
        - git-repo: '${TESTDEF_REPO}'
          revision: '${TESTDEF_REVISION}'
          testdef: '${TARGET_SESSION}'
          parameters:
            CONFIG: '${TARGET_CONFIG}'
            PUB_KEY: '${PUBLIC_KEY}'
  - command: submit_results
    parameters:
      server: '${BUNDLE_SERVER}'
      stream: '${BUNDLE_STREAM}'
device_group:
  - count: 1
    device_type: '${HOST_DEVICE_TYPE}'
    role: host
    #TODO Remove these tags (or turn into a substitution) once this template
    #     gets used for the uinstance.
    tags:
      - tcwg #IMPORTANT - ciadmin can submit anywhere, so main instance jobs really need this tag
             #Otherwise they can land on machine that we cannot forward sockets to.
  - count: 1
    device_type: '${TARGET_DEVICE_TYPE}'
    role: target
    #TODO Remove these tags (or turn into a substitution) once this template
    #     gets used for the uinstance.
    tags:
      - armv8 #IMPORTANT - ciadmin can submit anywhere, so main instance jobs really need this tag
              #Otherwise they can land on machine that we cannot forward sockets to.
              #Here we have picked a tag that just happens not to used on any restricted machines.
              #We cannot reuse tcwg, as there is only one tcwg kvm.
              #This also means that this template cannot work with non-kvm targets.
